server:
  port: 8083

spring:
  application:
    name: ticket
  datasource:
    url: jdbc:mysql://localhost:3306/dt_ticket?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/