server:
  port: 8081

spring:
  application:
    name: user
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com/mypro/user/model

logging:
  level:
    com:
      example:
        mapper : debug