server:
  port: 8761

spring:
  application:
    name: registry
  security:
    user:
      name: root
      password: root




eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka


